version: "3.7"
services:
  node:
    build:
      context: .
      target: ${ENVIRONMENT:-production-pseudo}
    volumes:
      - .:/usr/local/app/hello-google-apps-script
      - ~/.config/gcloud:/root/.config/gcloud
      - homedir:/root

  gcloud:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

volumes:
  homedir:
